version: '3'
services:
    nextjs:
        build: ./
        networks:
            - "nextjs.network"
        ports:
            - "3000:3000"
    nginx:
        image: nginx
        volumes:
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
        ports:
            - "80:80"
        networks:
            - "nextjs.network"
        depends_on:
            - nextjs


networks:
    nextjs.network:
