"""database migrated

Revision ID: 7dd5317b592a
Revises: a34146d64150
Create Date: 2020-09-12 11:11:55.596019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd5317b592a'
down_revision = 'a34146d64150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'days', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'days', type_='unique')
    # ### end Alembic commands ###
