"""database migrated

Revision ID: 89e6237969bb
Revises: 86708a8ed216
Create Date: 2020-09-11 09:26:25.769146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e6237969bb'
down_revision = '86708a8ed216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'exercises', ['id'])
    op.create_unique_constraint(None, 'routines', ['id'])
    op.drop_constraint('user_username_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.drop_constraint(None, 'routines', type_='unique')
    op.drop_constraint(None, 'exercises', type_='unique')
    # ### end Alembic commands ###
