"""database migrated

Revision ID: a34146d64150
Revises: 73499c913288
Create Date: 2020-09-11 21:50:33.382166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a34146d64150'
down_revision = '73499c913288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_chosen', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('day_identifier',
    sa.Column('routine_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('day_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], )
    )
    op.create_unique_constraint(None, 'exercises', ['id'])
    op.create_unique_constraint(None, 'routines', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routines', type_='unique')
    op.drop_constraint(None, 'exercises', type_='unique')
    op.drop_table('day_identifier')
    op.drop_table('days')
    # ### end Alembic commands ###
